dist: xenial
language: python
sudo: false

addons:
   apt:
     update: true


matrix:
  include:

    - name: "docs"
      python: 3.6
      env: DISTRIB="conda"
      before_script:
        - conda install -c conda-forge mpi4py pandoc
        - pip install -r requirements/requirements-docs.txt
        - pip install -r requirements/requirements-tutorials.txt
        - pip install -r requirements/requirements-extras.txt
      script: cd doc && make html

install:
  - if [[ "${DISTRIB}" == "conda" ]];
    then
      py_major=${TRAVIS_PYTHON_VERSION:0:1};
      wget https://repo.continuum.io/miniconda/Miniconda${py_major}-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda;
      source "$HOME/miniconda/etc/profile.d/conda.sh";
      conda config --set always_yes yes;
      conda update conda;
      sed -i "s/python>=[0-9]\.[0-9]/python=${TRAVIS_PYTHON_VERSION}/g" requirements/environment.yml;
      conda env create -f requirements/environment.yml;
      conda activate elephant;
      conda uninstall -y mpi4py;
      pip list;
    else
      pip install -r requirements/requirements.txt;
    fi

  - pip -V
  - pip install coverage coveralls nose
  - python setup.py install
  - python -c "from elephant.spade import HAVE_FIM; assert HAVE_FIM"
  - pip list
  - python --version

script:
  nosetests --with-coverage --cover-package=elephant
