name: Build Wheels

# Trigger the workflow on push to master. (this is equal to: PR is merged)
on:
  push:
    branches:
      - master
  pull_request_review:
    types: [ submitted ]
  pull_request:
    branches:
      - master
    types:
      #- assigned
      #- unassigned
      #- labeled
      #- unlabeled
      - opened
      #- edited
      #- closed
      - reopened
      - synchronize
      #- converted_to_draft
      #- ready_for_review
      #- locked
      #- unlocked
      #- review_requested
      #- review_request_removed
      #- auto_merge_enabled
      #- auto_merge_disabled

# Building wheels on Ubuntu and Windows systems
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]
        #os: [macos-11]

    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel==2.16.2

      - name: Install libomp
        if: runner.os == 'macOS'
        run: brew install libomp

      - name: Build wheels
        if: runner.os == 'Windows' || runner.os == 'Linux'
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_SKIP: "cp27-* cp33-* cp34-* cp35-* cp36-* cp37-* pp*"
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.8"
          CIBW_ARCHS: "auto64"

      - name: Build wheels
        if: runner.os == 'macOS'
        run: |
          brew install libomp llvm
          export CC=/usr/local/opt/llvm/bin/clang
          export CXX=/usr/local/opt/llvm/bin/clang++
          export LDFLAGS="-L/usr/local/opt/libomp/lib"
          export CPPFLAGS="-I/usr/local/opt/libomp/include"
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_SKIP: "cp27-* cp33-* cp34-* cp35-* cp36-* cp37-* pp*"
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.8"
          CIBW_ARCHS: "auto64"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
