name: Elephant -- all tests

on:
  pull_request:
    branches: [master]
    types: [synchronize, opened, reopened, ready_for_review]

  # run checks on any change of master, including merge of PRs
  push:
    branches: [master]

jobs:
  build-and-test:
    name: Test on (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # "macos-latest", "windows-latest"
        os: ["ubuntu-latest", ]
    steps:
      - uses: actions/checkout@v2
        with:
          python-version: 3.8
      - name: Get current year-month
        id: date
        run: echo "::set-output name=date::$(date+'%Y-%m')"
      - uses: actions/cache@v2
        # the cache for python package is reset:
        #   * every month
        #   * when requirements/requirements_testing change
        id: cache-venv
        with:
          path: ~/test_env
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/requirements_testing.txt') }}-${{ steps.date.outputs.date }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Install dependencies
        run: |
          # this is for datalad and download testing datasets
          # sudo apt install git git-annex
          # needed for correct operation of git/git-annex/DataLad
          # git config --global user.email "neo_ci@fake_mail.com"
          # git config --global user.name "neo CI"
          # create an environment and install everything
          python -m venv ~/test_env
          source ~/test_env/bin/activate
          python -m pip install --upgrade pip
          # pip install -r requirements.txt
          pip install -r requirements/requirements-tests.txt
          pip install pytest-cov coveralls
          # pip install -r requirements_testing.txt
          pip install -e .
      - name: Test with pytest
        run: |
          source ~/test_env/bin/activate
          # only neo.rawio and neo.io
          pytest --cov=elephant
