name: Compile fim.cpp on macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_macos:
    name: Compile on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, macos-12, macos-13, macos-14]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: |
          brew install llvm libomp

#      - name: Compile fim.cpp
#        run: |
#          /opt/homebrew/opt/llvm/bin/clang++ -o fim.o -c elephant/spade_src/src/fim.cpp \
#            -Ielephant/spade_src/include \
#            -I/opt/homebrew/opt/llvm/include \
#            -Xpreprocessor -fopenmp \
#            -std=gnu++17 \
#            -O3 -pedantic -Wextra -Weffc++ -Wunused-result -Werror -Werror=return-type

      - name: Compile C++ Code
        run: |
            cd elephant/spade_src/src/fim.cpp
            clang++ -std=gnu++17 -shared -undefined dynamic_lookup -o fim.so fim.cpp FPGrowth.cpp -I/usr/local/include/python3.10

      - name: Upload compiled artifacts
        uses: actions/upload-artifact@v3
        with:
          name: fim-compiled
          path: fim.so
